AjaxPostContacts/Models/ContactModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace AjaxPostContacts.Models
{
    public class ContactModel
    {
        public string? Name { get; set; }
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime? RecordDate { get; set; }
        public int? Age { get; set; }
        public string? City { get; set; }

    }

    public enum Cities
    {
        İstanbul,
        Ankara,
        İzmir,
        Bursa,
        Adana
    }
}

AjaxPostContacts/Models/ErrorViewModel.cs
using System;

namespace AjaxPostContacts.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AjaxPostContacts/Controllers/ContactController.cs
using AjaxPostContacts.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System;
using Newtonsoft.Json.Linq;

namespace AjaxPostContacts.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [HttpPost]
        public ActionResult AddContact(string name, DateTime recorddate, int age, string city)
        {
            var contact = new ContactModel();

            contact.Name = name;
            contact.RecordDate = recorddate;
            contact.Age = age;
            contact.City = city;

            return new JsonResult(new { data = contact });
        }
    }
}

AjaxPostContacts/Controllers/HomeController.cs
using AjaxPostContacts.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace AjaxPostContacts.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
    }
}

AjaxPostContacts/Views/Contact/Index.cshtml
@{
    ViewData["Title"] = "Contact Page";
}

@model AjaxPostContacts.Models.ContactModel

<div class="row">
    <div class="col-md-8 col-lg-offset-4">
        <h2>Add Contact</h2>
        <br />
        <span>Name: </span> @Html.TextBoxFor(x => x.Name, new{@class = "form-control"})<br />
        <span>Date: </span> @Html.TextBoxFor(x => x.RecordDate, new{@class = "form-control", @type = "date"})<br />
        <span>Age: </span> @Html.TextBoxFor(x => x.Age, new{@class = "form-control"})<br />
        <span>City: </span> @Html.DropDownListFor(x => x.City, new SelectList(Enum.GetValues(typeof(Cities))), "Select City")<br />
        <button class="btn btn-default" onclick='SaveContact()'>Save</button> <br /> <br />

    </div>
</div>

<div class="row">
    <div class="col-md-8 col-lg-offset-3">
        <h2>New Contact List</h2><br />
        <table id="myTable" class="table-striped">
            <tr>
                <th>Name</th>
                <th>Date</th>
                <th>Age</th>
                <th>City</th>
            </tr>
        </table>
    </div>
</div>

<style>
    #myTable tr th{
        color: white;
        width: 300px;
        height: 40px;
        text-decoration: solid;
        background-color: green;
        padding: 10px;
    }
</style>

<script type="text/javascript">

    function SaveContact() {
        var Name = $("#Name").val();
        var RecordDate = $("#RecordDate").val();
        var Age = parseInt($("#Age").val());
        var City = $("#City").val();

        $.ajax({
            type: "POST",
            url: "/Contact/AddContact",
            data: {name : Name, recorddate : RecordDate, age : Age, city : City},
            success: function (result) {

                var json = JSON.parse(JSON.stringify(result.data));

                $("#myTable").append("<tr><td>" +
                    json['name'] + "</td><td>" +
                    new Date(json['recordDate']).toDateString() + "</td><td>" +
                    json['age'] + "</td><td>" +
                    json['city'] + "</td></tr>");
                $("#Name").val("");
                $("#RecordDate").val("");
                $("#Age").val("");
                $("#City").val("");
            },
            failure: function (result) {
                alert(result.responseText);
            }
        })
    };

</script>

AjaxPostContacts/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AjaxPostContacts</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AjaxPostContacts</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contact" asp-action="Index">Contact</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - AjaxPostContacts - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>